-- https://app.snowflake.com/marketplace/listing/GZSTZIDI09G/predicthq-intelligent-event-data-attended-events-munich-sample



-- Create a dedicated database and schema for the new views
CREATE DATABASE IF NOT EXISTS GHIMMOHMOH_SAMPLE;
CREATE SCHEMA IF NOT EXISTS GHIMMOHMOH_SAMPLE.PUBLIC;

-- Create the limited attributes view
CREATE VIEW IF NOT EXISTS GHIMMOHMOH_SAMPLE.PUBLIC.VIEW3 AS
SELECT TITLE, CATEGORY, "DESCRIPTION", EVENT_START, EVENT_END, GEO, PREDICTED_EVENT_SPEND_HOSPITALITY, PREDICTED_EVENT_SPEND_TRANSPORTATION, FORMATTED_ADDRESS, PHQ_ATTENDANCE, PHQ_LABELS  from INTELLIGENT_EVENT_DATA_ATTENDED_EVENTS_MUNICH__SAMPLE.PREDICTHQ.PREDICTHQ_ATTENDED_EVENTS_MUNICH

-- Confirm the view was created correctly
SELECT * FROM GHIMMOHMOH_SAMPLE.PUBLIC.VIEW3;
